app = "renzoagostini-api"
primary_region = "ams"

[build]
  dockerfile = "docker/Dockerfile.server"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = "false"

[[mounts]]
  source = "renzoagostini_api_data"
  destination = "/data"

[[mounts]]
  source = "renzoagostini_api_assets"
  destination = "/app/wwwroot"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80
